# Generated by Django 2.2.4 on 2021-04-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_spanish', models.CharField(max_length=100)),
                ('name_english', models.CharField(max_length=100)),
                ('slug_spanish', models.SlugField(max_length=100)),
                ('slug_english', models.SlugField(max_length=100)),
                ('code_alpha_two', models.CharField(max_length=5)),
                ('code_alpha_three', models.CharField(max_length=5)),
            ],
        ),
    ]
